# Generated by Django 5.2 on 2025-09-17 01:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TIL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.SlugField(unique_for_date="created")),
                ("body", models.TextField()),
                (
                    "card_image",
                    models.URLField(
                        blank=True,
                        help_text="URL to image for social media cards",
                        null=True,
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False,
                        help_text="Draft TILs do not show in index pages but can be visited directly if you know the URL",
                    ),
                ),
                (
                    "linkedin_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically post to LinkedIn when published",
                    ),
                ),
                (
                    "linkedin_custom_text",
                    models.TextField(
                        blank=True,
                        help_text="Custom text for LinkedIn post (leave blank to use body)",
                        null=True,
                    ),
                ),
                (
                    "linkedin_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this TIL has been posted to LinkedIn",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="core.enhancedtag")),
            ],
            options={
                "verbose_name": "TIL",
                "verbose_name_plural": "TILs",
                "ordering": ["-created"],
            },
        ),
    ]
