# Generated by Django 5.2 on 2025-09-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("til", "0001_initial"),
    ]

    operations = [
        # Empty migration to mark that card_image field was already added manually
    ]