# Generated by Django 5.2 on 2025-09-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("til", "0002_add_card_image_fake"),
    ]

    operations = [
        migrations.AddField(
            model_name="til",
            name="linkedin_custom_text",
            field=models.TextField(
                blank=True,
                help_text="Custom text for LinkedIn post (leave blank to use body)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="til",
            name="linkedin_enabled",
            field=models.BooleanField(
                default=False, help_text="Automatically post to LinkedIn when published"
            ),
        ),
        migrations.AddField(
            model_name="til",
            name="linkedin_posted",
            field=models.BooleanField(
                default=False, help_text="Whether this TIL has been posted to LinkedIn"
            ),
        ),
    ]