# Generated by Django 5.2 on 2025-09-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("til", "0003_add_linkedin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="til",
            name="card_image",
            field=models.URLField(
                blank=True, help_text="URL to image for social media cards", null=True
            ),
        ),
    ]
