# Generated by Django 5.2 on 2026-06-10 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("til", "0003_rename_image_alt_to_image_caption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="til",
            name="linkedin_custom_text",
        ),
        migrations.RemoveField(
            model_name="til",
            name="linkedin_enabled",
        ),
        migrations.RemoveField(
            model_name="til",
            name="linkedin_posted",
        ),
    ]
