# Generated by Django 5.2 on 2026-07-03 23:22

import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Schedule this content to be published at a future date and time",
                        null=True,
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False, help_text="Legacy field. Use 'status' instead."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="Draft entries are only visible to logged-in users with the preview link",
                        max_length=10,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Short description shown on the projects grid card (markdown)"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Full write-up shown on the detail page (markdown)",
                    ),
                ),
                (
                    "repo_url",
                    models.URLField(blank=True, help_text="Source code repository URL"),
                ),
                (
                    "live_url",
                    models.URLField(blank=True, help_text="Live site or demo URL"),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated technologies, e.g. Django, PostgreSQL, HTMX",
                        max_length=255,
                    ),
                ),
                (
                    "project_status",
                    models.CharField(
                        choices=[
                            ("wip", "Work in Progress"),
                            ("active", "Active"),
                            ("shipped", "Shipped"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Lifecycle state of the project itself (distinct from publish status)",
                        max_length=10,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When work on the project began"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When the project shipped or was archived (blank = ongoing)",
                        null=True,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this project at the top of the grid",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers sort first in the curated grid",
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Screenshot or thumbnail for the card and social cards",
                        null=True,
                        upload_to="projects/images/%Y/%m/",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-start_date"],
            },
        ),
    ]
