# Generated by Django 5.2 on 2026-07-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_project_end_date_after_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Automatically set to the last time this content was saved",
            ),
        ),
    ]
