version: "3.8"

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  web:
    volumes:
      # Mount source code for live development changes
      - .:/app
      # But still use named volume for data directory
      - minimalwave-blog-data:/app/data
      # Keep media and static separate
      - ./media:/app/media
      - ./static:/app/static
    environment:
      # Development-specific environment variables
      - DJANGO_SETTINGS_MODULE=minimalwave-blog.settings.development
      - DEBUG=True
      # Override for localhost development
      - LINKEDIN_REDIRECT_URI=http://localhost:8000/admin/linkedin/auth/callback/
      # Add development superuser (optional)
      # - DJANGO_SUPERUSER_USERNAME=dev
      # - DJANGO_SUPERUSER_PASSWORD=dev123
      # - DJANGO_SUPERUSER_EMAIL=dev@example.com
    # Enable hot reloading
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    # For better development experience
    stdin_open: true
    tty: true

volumes:
  minimalwave-blog-data:
  postgres_data: