version: "3.8"

services:
  web:
    build:
      context: .
      args:
        - DJANGO_SETTINGS_MODULE=minimalwave_blog.settings.production
    image: minimalwave-blog:production
    container_name: minimalwave-blog-production
    ports:
      - "8000:8000"
    volumes:
      - minimalwave-blog-prod-data:/app/data
      - ./media:/app/media
      - ./static:/app/static
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    environment:
      - DJANGO_SETTINGS_MODULE=minimalwave_blog.settings.production
      # Load these values from .env file in production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOST=${ALLOWED_HOST}
    restart: unless-stopped
    depends_on:
      - db
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf

  db:
    image: postgres:14
    container_name: minimalwave-blog-prod-db
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped

volumes:
  minimalwave-blog-prod-data:
  postgres_prod_data:
