# Generated by Django 5.2 on 2025-09-17 02:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeriesEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order within the series"),
                ),
                (
                    "part_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for this part (e.g., 'Part 1: Introduction')",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this entry's role in the series",
                    ),
                ),
                ("added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_memberships",
                        to="blog.entry",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_entries",
                        to="core.series",
                    ),
                ),
            ],
            options={
                "verbose_name": "Series Entry",
                "verbose_name_plural": "Series Entries",
                "ordering": ["order", "added"],
                "unique_together": {("series", "entry")},
            },
        ),
    ]