# Generated by Django 5.2 on 2026-01-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_simplify_taxonomy"),
    ]

    operations = [
        # Note: The content and slug indexes were already removed in 0003_simplify_taxonomy
        # when those fields were deleted. Only the is_active index rename is needed.
        migrations.RenameIndex(
            model_name="enhancedtag",
            new_name="core_enhanc_is_acti_816df5_idx",
            old_name="core_enhanc_is_acti_idx",
        ),
    ]
