# Generated by Django 5.2 on 2026-01-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_simplify_taxonomy"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="enhancedtag",
            name="core_enhanc_content_9af629_idx",
        ),
        migrations.RemoveIndex(
            model_name="enhancedtag",
            name="core_enhanc_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="enhancedtag",
            new_name="core_enhanc_is_acti_816df5_idx",
            old_name="core_enhanc_is_acti_idx",
        ),
    ]
