# Generated by Django 5.2 on 2026-01-30 22:42

from django.db import migrations


def remove_old_indexes(apps, schema_editor):
    """Remove indexes that were added in migration 0003 but are no longer needed"""
    with schema_editor.connection.cursor() as cursor:
        # Try to drop indexes if they exist
        for index_name in ['core_enhanc_slug_idx', 'core_enhanc_is_acti_idx']:
            try:
                cursor.execute(f'DROP INDEX IF EXISTS {index_name}')
            except Exception:
                # Index doesn't exist, that's fine
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_old_indexes"),
    ]

    operations = [
        # Remove indexes using RunPython since they were created via RunPython in 0003
        migrations.RunPython(
            remove_old_indexes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
