# Generated by Django 5.2 on 2026-01-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_old_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="enhancedtag",
            name="core_enhanc_content_9af629_idx",
        ),
        migrations.RemoveIndex(
            model_name="enhancedtag",
            name="core_enhanc_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="enhancedtag",
            name="core_enhanc_is_acti_idx",
        ),
    ]
