# Generated by Django 5.2 on 2026-06-10 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_enhancedtag_core_enhanc_content_9af629_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContentLinkedIn",
        ),
    ]
