# Generated by Django 5.2 on 2026-06-11 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogmark_tags_alter_entry_tags"),
        ("core", "0006_remove_linkedin"),
        ("til", "0004_remove_linkedin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EnhancedTag",
        ),
    ]
