version: "3.8"

services:
  web:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    image: minimalwave-blog
    container_name: minimalwave-blog-container
    ports:
      - "8000:8000"
    volumes:
      - minimalwave-blog-data:/app/data
      - ../../media:/app/media
      - ../../static:/app/static
    env_file:
      - ../../.env
    environment:
      - DJANGO_SETTINGS_MODULE=minimalwave-blog.settings.development
      # Override LinkedIn redirect URI for local development
      - LINKEDIN_REDIRECT_URI=http://localhost:8000/admin/linkedin/auth/callback/
      # For creating a superuser on first run, uncomment and set these:
      # - DJANGO_SUPERUSER_USERNAME=admin
      # - DJANGO_SUPERUSER_PASSWORD=adminpassword
      # - DJANGO_SUPERUSER_EMAIL=admin@example.com
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: minimalwave-blog-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=minimalwave
    restart: unless-stopped

volumes:
  minimalwave-blog-data:
  postgres_data:
