# Generated by Django 5.2 on 2025-09-17 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="Minimal Wave Blog",
                        help_text="The title of your blog",
                        max_length=100,
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="A personal blog with minimal wave aesthetics",
                        help_text="The description of your blog",
                    ),
                ),
                (
                    "header_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo to display in the header (optional)",
                        null=True,
                        upload_to="site_settings/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Site favicon (optional)",
                        null=True,
                        upload_to="site_settings/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Authorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "authorships",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Blogmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Schedule this content to be published at a future date and time",
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(unique_for_date="created")),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False, help_text="Legacy field. Use 'status' instead."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="Draft entries are only visible to logged-in users with the preview link",
                        max_length=10,
                    ),
                ),
                ("url", models.URLField()),
                ("commentary", models.TextField()),
                (
                    "via",
                    models.URLField(
                        blank=True,
                        help_text="URL of where you found the link",
                        null=True,
                    ),
                ),
                (
                    "via_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of where you found the link",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="core.enhancedtag")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Schedule this content to be published at a future date and time",
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(unique_for_date="created")),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False, help_text="Legacy field. Use 'status' instead."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="Draft entries are only visible to logged-in users with the preview link",
                        max_length=10,
                    ),
                ),
                ("summary", models.TextField()),
                ("body", models.TextField()),
                (
                    "card_image",
                    models.URLField(
                        blank=True,
                        help_text="URL to image for social media cards",
                        null=True,
                    ),
                ),
                (
                    "linkedin_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically post to LinkedIn when published (currently disabled)",
                    ),
                ),
                (
                    "linkedin_custom_text",
                    models.TextField(
                        blank=True,
                        help_text="Custom text for LinkedIn post (leave blank to use summary)",
                        null=True,
                    ),
                ),
                (
                    "linkedin_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this entry has been posted to LinkedIn",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        through="blog.Authorship",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="core.enhancedtag")),
            ],
            options={
                "verbose_name_plural": "entries",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="authorship",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.entry"
            ),
        ),
    ]
