# Generated by Django 5.2 on 2025-05-26 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'authorships',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique_for_date='created')),
                ('is_draft', models.BooleanField(default=False, help_text='Draft entries do not show in index pages but can be visited directly if you know the URL')),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('card_image', models.URLField(blank=True, help_text='URL to image for social media cards', null=True)),
                ('authors', models.ManyToManyField(blank=True, through='blog.Authorship', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='authorship',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.entry'),
        ),
        migrations.CreateModel(
            name='Blogmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique_for_date='created')),
                ('is_draft', models.BooleanField(default=False, help_text='Draft entries do not show in index pages but can be visited directly if you know the URL')),
                ('url', models.URLField()),
                ('commentary', models.TextField()),
                ('via', models.URLField(blank=True, help_text='URL of where you found the link', null=True)),
                ('via_title', models.CharField(blank=True, help_text='Title of where you found the link', max_length=200, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
