# Generated by Django 5.2 on 2026-07-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_prune_legacy_migration_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmark",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Automatically set to the last time this content was saved",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Automatically set to the last time this content was saved",
            ),
        ),
    ]
