# Generated by Django 5.2 on 2025-09-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_sync_linkedin_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="linkedin_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Automatically post to LinkedIn when published (currently disabled)",
            ),
        ),
        migrations.AlterField(
            model_name="linkedincredentials",
            name="access_token",
            field=models.TextField(blank=True, default='', help_text="LinkedIn OAuth access token"),
        ),
        migrations.AlterField(
            model_name="linkedincredentials",
            name="refresh_token",
            field=models.TextField(
                blank=True, help_text="LinkedIn OAuth refresh token", null=True
            ),
        ),
        migrations.AlterField(
            model_name="linkedincredentials",
            name="token_expires_at",
            field=models.DateTimeField(null=True, blank=True, help_text="When the access token expires"),
        ),
        migrations.AlterField(
            model_name="linkedinpost",
            name="post_text",
            field=models.TextField(blank=True, default='', help_text="Text content posted to LinkedIn"),
        ),
    ]
