name: Build and Deploy to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          # Check if lock file is up to date, regenerate if needed
          poetry check || poetry lock
          poetry install --no-interaction --no-ansi --no-root

      - name: Validate migrations
        run: |
          # Use in-memory SQLite for CI validation
          export DATABASE_URL="sqlite:///:memory:"
          poetry run python manage.py makemigrations --check --dry-run
          poetry run python manage.py check

      - name: Test migrations in clean environment
        run: |
          # Test that migrations can be applied from scratch (like production)
          # Use in-memory SQLite for CI testing
          export DATABASE_URL="sqlite:///:memory:"
          poetry run python manage.py migrate --run-syncdb
          poetry run python manage.py check

      - name: Run basic tests
        run: |
          # Use in-memory SQLite for CI testing
          export DATABASE_URL="sqlite:///:memory:"
          poetry run python manage.py test blog.tests.BlogTestCase.test_blog_entry blog.tests.BlogTestCase.test_blogmark blog.tests.BlogTestCase.test_til_detail

      - name: Validate templates
        run: |
          # Use in-memory SQLite for CI testing
          export DATABASE_URL="sqlite:///:memory:"
          poetry run python manage.py test blog.tests.TemplateValidationTests.test_all_templates_compile

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          # Set environment to production for the build
          docker buildx build --platform linux/amd64 -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/minimalwave-blog:${{ github.sha }} \
                      --build-arg DJANGO_SETTINGS_MODULE=minimalwave-blog.settings.production .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/minimalwave-blog:${{ github.sha }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "minimalwave-blog"
          images: "${{ secrets.REGISTRY_LOGIN_SERVER }}/minimalwave-blog:${{ github.sha }}"
          
      - name: Restart App Service
        run: |
          az webapp restart --name minimalwave-blog --resource-group minimalwave-blog-rg
          
      - name: Wait for deployment
        run: sleep 30
        
      - name: Smoke test deployment
        run: |
          echo "Testing homepage..."
          curl -f -s -o /dev/null https://jamesfishwick.com/ || (echo "Homepage failed" && exit 1)
          echo "✓ Homepage OK"
          
          echo "Testing blog post..."
          curl -f -s -o /dev/null https://jamesfishwick.com/2025/jul/2/model-autophagy-disorder-ai-will-eat-itself/ || (echo "Blog post failed" && exit 1)
          echo "✓ Blog post OK"
          
          echo "All smoke tests passed!"

      - name: Azure Logout
        run: az logout
